# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  languageName: English
  weight: 1
  contentDir: content/en
  

# Chinese language
zh:
  languageCode: zh-Hans
  languageName: 中文
  weight: 2
  contentDir: content/zh
  title: 王乐文
  params:
    header:
      navbar:
        enable: true
        blox: "navbar"
        fixed_to_top: true
        show_search: true
        show_theme_chooser: true
        logo:
          text: "王乐文"
  menu:
    main:
      - name: 关于我
        url: /
        weight: 10
      - name: 发表论文
        url: publication/
        weight: 25
      - name: 经历
        url: experience/
        weight: 40
      - name: 画廊
        url: gallery/
        weight: 55
      - name: 博客
        url: blog/
        weight: 70

